### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Maigo96** [s4n7h0/xvwa#14]
OK... I'm stuck... I'm installing on top of XAMPP.

This is my config file
![config](https://cloud.githubusercontent.com/assets/16862231/12535575/03e7eb40-c2cb-11e5-9a61-da2744d2d680.PNG)

When I visit localhost I get this:
![page](https://cloud.githubusercontent.com/assets/16862231/12535573/ea71eb48-c2ca-11e5-9f87-4a11f155f0eb.PNG)

I get errors in the source
![underlyingsourse](https://cloud.githubusercontent.com/assets/16862231/12535577/1d349f44-c2cb-11e5-8de7-e32e22900a30.PNG)

Any ideas?

**Comment by Barsomisco** [comment]
I'm using WAMP and I had the same problem.
I solved it by creating a database in phpmyadmin called xvwa with a user called root and with the password root.

**Comment by s4n7h0** [comment]
@Maigo96 yes. I can see the error is because of database access. Make sure the username and password for Mysql is correct. Also create a database in mysql using command line or phpmyadmin as suggested by @Barsomisco  I will be also releasing an pre-configured iso soon to make things more easy :)

**Comment by Barsomisco** [comment]
@s4n7h0 I also got another error that might be something to look into aswell:
"Deprecated: mysql_connect(): the mysql extension is deprecated and will be removed in the future: use mysqli or PDO...."
At the moment I simply ignore it by adding this line in php.ini:
`error_reporting = E_ALL ^ E_DEPRECATED`

**Comment by s4n7h0** [comment]
@Barsomisco Is that error or warning ??

**Comment by Barsomisco** [comment]
@s4n7h0 I guess it is an error since it kinda break the website:
![depr](https://cloud.githubusercontent.com/assets/7132170/13293216/16abdc2a-db1f-11e5-802d-7da2e8cc9375.png)

**Comment by s4n7h0** [comment]
@Barsomisco Oh yea. can you please use error_reporting(E_ALL ^ E_DEPRECATED); option to ignore those errors as you suggested earlier. mysql_connect() is required in some part of the application.

**Comment by s4n7h0** [comment]
@Barsomisco Hey, I made a short script for auto configuring xvwa with latest repo from GitHub. This issue should be closed with it https://github.com/s4n7h0/Script-Bucket/blob/master/Bash/xvwa-setup.sh
