### ISSUE TITLE
Warning \xvwa-master\header.php on line 18

### ISSUE THREAD

**Issue by karlito62** [s4n7h0/xvwa#15]
I install xvwa on a local network under Windows 10 when I runhttp://localhost:8080/xvwa-master/setup/ I have the following error message

Warning: include(G:\serveur\root\xvwa-master..\/xvwa/config.php): failed to open stream: No such file or directory in G:\serveur\root\xvwa-master\header.php on line 18

Warning: include(): Failed opening 'G:\serveur\root\xvwa-master..\/xvwa/config.php' for inclusion (include_path='.;C:\php\pear') in G:\serveur\root\xvwa-master\header.php on line 18

**Comment by s4n7h0** [comment]
@karlito62 it looks like php interpreter is not able to locate the file path. please see instructions carefully.  https://github.com/s4n7h0/xvwa#instructions.
