### ISSUE TITLE
blank screen 

### ISSUE THREAD

**Issue by AliBawazeEer** [s4n7h0/xvwa#16]
Hi Team ,
## first thank you for the effort on running such deliberate vulnerable app 

i am trying to install the application on virtualbox running ubuntu , LAMP stack installed , phpmyadmin also installed .. database created 

however every time i try to access the page all i get blank screen 

http://192.168.56.103/xvwa/setup/

drwxrwxrwx 9 root root  4096 May 28 17:48 xvwa

<?php
$XVWA_WEBROOT = '';

$host = "localhost";
$dbname = 'xvwa';
$user = 'root';
$pass = 'pentester';
$conn = mysql_connect($host,$user,$pass);
$conn = mysql_select_db($dbname);
$conn1 = new PDO("mysql:host=$host;dbname=$dbname", $user, $pass);
$conn1->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
?>

---

file_uploads = On
allow_url_fopen = on
allow_url_include = on

can anyone suggest what went wrong , thank you

**Comment by AliBawazeEer** [comment]
i ran the bash script for the installation ,,, looks all setup .. still i get blank screen 

running ubuntu 16 LAMP server ... apache

**Comment by s4n7h0** [comment]
@AliBawazeEer mind to share the screen or connect me on email ? it would be easy to quickly fix. I'm sure there must be something very silly you must be missing.

**Comment by AliBawazeEer** [comment]
@s4n7h0  ,, appreciate your assistance ... i manage to fix it.. i guess made a mistake while trying to install the script on php7 but when i ran it on php 5 it worked . . thank you

**Comment by s4n7h0** [comment]
@AliBawazeEer Glad to know that. Hope to see some feedback and blogpost :)

**Comment by A7med11samir** [comment]
hi i have the same problem .. i tried many times to solve it
![Screenshot_2020-09-12_10-48-07](https://user-images.githubusercontent.com/38285511/92999545-f3216780-f521-11ea-89a3-5a77f7a59075.png)
