### ISSUE TITLE
Code needs to be updated to run with PHP 7.0.x

### ISSUE THREAD

**Issue by imdadvs** [s4n7h0/xvwa#17]
_mysql_connect_, _mysql_fetch_array()_, _mysql_select_db()_ and other MySQL PHP functions are used which doesn't work with updated version of PHP. I had to replace it with mysqli_connect and similarly for others. 
Also  this error is common with new version of PHP
_PHP Notice:  Undefined variable: input in C:\xvwa\vulnerabilities\xpath\home.php on line 35_ 

Code needs to be updated to run with PHP 7.0.x

Eg : _PHP Fatal error:  Uncaught Error: Call to undefined function mysql_select_db()_

**Comment by s4n7h0** [comment]
@imdadvs Thanks for the input. That would surely a bit lot of code changes. I will look into it for next update release.

**Comment by s4n7h0** [comment]
@imdadvs hey, changes are done :) Thanks for suggesting.
