### ISSUE TITLE
login redirection 

### ISSUE THREAD

**Issue by AliBawazeEer** [s4n7h0/xvwa#19]
Hi .. facing issue

whenever i login and enter admin admin , i get redirected to http://localhost/var/www/html/xvwa/login.php  ?? 

The requested URL /var/www/html/xvwa/login.php was not found on this server.

Apache/2.4.18 (Ubuntu) Server at 192.168.56.102 Port 80

pwd : /var/www/html/xvwa/ 
ls : login.php exist 

Thank you

**Comment by AliBawazeEer** [comment]
even when you look at the images , you find `( <img src="/var/www/html/xvwa/img/XVWA4589.png" height="130" weight="20/" data-pin-nopin="true"> 
`

**Comment by s4n7h0** [comment]
@AliBawazeEer /var/www/html should be your web root directly and this path is automatically picked up by web servers. You should be using localhost/xvwa/login.php instead. Also ensure you use correct configuration parameters specified here https://github.com/s4n7h0/xvwa#manual-installation-method
