### ISSUE TITLE
something wrong 

### ISSUE THREAD

**Issue by qdwjfufu** [s4n7h0/xvwa#20]
unbutu14.04 mysql apache2 php5.5.9 
and it can't work correctly
only see xvwa on the top of left

okey 
 php5-mysql need install

**Comment by s4n7h0** [comment]
@qdwjfufu this should be because your  $XVWA_WEBROOT value must be wrong. Please recheck or use the auto setup script https://github.com/s4n7h0/Script-Bucket/blob/master/Bash/xvwa-setup.sh
