### ISSUE TITLE
Have  u tested the "Unrestricted File Upload "?

### ISSUE THREAD

**Issue by qdwjfufu** [s4n7h0/xvwa#21]
i have seen the code of the "Unrestricted File Upload ",but i can't upload a image
i have a test of dvwa ,that's ok
pls help me ,and give me the answer,thank u!

**Comment by s4n7h0** [comment]
@qdwjfufu thanks for the feedback. yes. the code had some path issues. please get the new pull I have fixed this issue. So closing this issue. Feel free to reopen it if you still facing this issue.

**Comment by NitescuLucian** [comment]
@s4n7h0 in VM I am still getting ```There was an error uploading the file, please try again!```
