### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by nauliajati** [s4n7h0/xvwa#23]
hi, i'm confused after the installation xvwa on my machine i found blank page, i'm already follow up the instruction step by step with correctly, but same...
can u hel me please?
![screenshot from 2016-10-24 00-46-02](https://cloud.githubusercontent.com/assets/8980647/19628249/aa3a1d6c-9983-11e6-862c-a0969adeb242.png)

**Comment by s4n7h0** [comment]
@404Ghost99 Possible issues could be. 
- mysql service is not started 
- mysql username/password is wrong. 

Please check for this and let me know if that works for you.

**Comment by s4n7h0** [comment]
@404Ghost99 are you still facing issue ? can I close this if it is resolved.

**Comment by nauliajati** [comment]
yeah i still facing this issue, hmm i not sure about that, i'm using nginx in kali linux for running xvwa, i think nginx or xvwa cannot run if use root user, what do you think? i still confused :disappointed:

**Comment by s4n7h0** [comment]
@404Ghost99 I have not tested on nginx. I doubt if this is something to do with the permission. Could you remove the folder, use the [auto setup script](https://github.com/s4n7h0/Script-Bucket/blob/master/Bash/xvwa-setup.sh) and pull it directly to webroot directory ? 

Also use default apache instead of nginx and see if it's working. if so, there should be some config issues in nginx. 

the script should work like below. 

```
MySQL found with Version: 5.6.30-1 Version: 5.6.27-2
Apache found with Version: 2.4.25-1 Version: 2.4.18-1
MySQL is down. Starting MySQL Service
Apache is down. Starting Apache Service
Enter mysql username : root
Enter mysql password : 
Enter the full web root path : /var/www/html
Cloning latest version of XVWA from GitHub
Cloning into '/var/www/html/xvwa'...
remote: Counting objects: 952, done.
remote: Total 952 (delta 0), reused 0 (delta 0), pack-reused 952
Receiving objects: 100% (952/952), 2.15 MiB | 202.00 KiB/s, done.
Resolving deltas: 100% (211/211), done.
Checking connectivity... done.
Setting XVWA configuration
Creating xvwa database
Enter password: 
XVWA Setup Finished Successfully. Happy hacking and happy learning !
```

**Comment by nauliajati** [comment]
i have already to use [auto setup script](https://github.com/s4n7h0/Script-Bucket/blob/master/Bash/xvwa-setup.sh) but still can't.. 
hmm .. i think nginx in my machine is trouble.. xvwa can't run if i'm using root user 

by the way what machine you use for running your xvwa? and u using apache right?

**Comment by s4n7h0** [comment]
@404Ghost99 yes. My Kali running with default Apache setup. I tested this with Ubuntu and Debian as well and it worked neat for me.  I highly doubt it should be issue with nginx settings. I'm closing this issue as this is not related to XVWA code base itself. Feel free to reopen this issue if you find a work around in ngnix setup. It would help other folks who prefer same way.

**Comment by leisipeisi** [comment]
Hi everyone,

I am currently facing the same issue. I have built a linux using yocto, including apache, php, mysql and proftpd.
The my.cnf has the following lines:
```
[client]
#password                                       = password
...
[mysqld]
user                                            = root
...
```
The XVWA config is:
```
<?php
$XVWA_WEBROOT = "";
$host = "localhost";
$dbname = 'xvwa';
$user = "root";
$pass = "";
$conn = new mysqli($host,$user,$pass,$dbname);
$conn1 = new PDO("mysql:host=$host;dbname=$dbname", $user, $pass);
$conn1->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
?>
```
I have created a database named xvwa and SQL Server is running:
```
/etc/init.d/mysqld status
 SUCCESS! MySQL running (1335)
```

Do you have any suggestion what to try to get it running? Any help is appreciated!

**Comment by AhmedMahmoudEG** [comment]
Hello guys i faced the same problem it was from mysql database users
i fixed it by create new user on mysql 
then installed the xvwa with the new user and it worked

**Comment by s4n7h0** [comment]
Hi @leisipeisi, 

The blank page is most likely because of the database connection. Are you able to shell into mysql console with the same username and password shown in the config and view the databases ? Do you see xvwa is listed there ?
