### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by nizarakbarm** [s4n7h0/xvwa#25]
i'm success in installation process but when i try to open localhost/xvwa, it only show blank page. Is there any dependency of bootstrap maybe?

**Comment by s4n7h0** [comment]
@elneunizar There is no dependencies except the apache and myql services itself. Have you used the automatic installation script mentioned here https://github.com/s4n7h0/xvwa#automatic-installation-methods 
could you also check following: 
- database is running ? 
- configuration is correct ? check config.php content as mentioned here  https://github.com/s4n7h0/xvwa#manual-installation-method 
-

**Comment by s4n7h0** [comment]
@elneunizar I have ported code to php version 7 and the previous errors was happening due to some depreciated functions being used. Please pull the updates and let me know if you face any issues.
