### ISSUE TITLE
Getting some Errors when try to setup.

### ISSUE THREAD

**Issue by SecurityFlaw** [s4n7h0/xvwa#31]
System: Windows 10 Professional
Webserver: XAMPP (Apache, MySQL, PHP)

Screenshot: https://i.imgur.com/HoUFh6F.png

config.php is correct. (User: "root", Password: "")

**Comment by SecurityFlaw** [comment]
Ok, i fixed it. This help's: https://i.imgur.com/CgmGFJi.png

**Comment by s4n7h0** [comment]
Glad to know you managed to figure out the issue and fixed it.
