### ISSUE TITLE
config.php Error

### ISSUE THREAD

**Issue by MuAql** [s4n7h0/xvwa#38]
When the config.php file is:
![image](https://user-images.githubusercontent.com/48137672/64986704-e85cd400-d8c7-11e9-9ea2-241c63589c02.png)

I got this Fatal error when I open the localhost/xvwa
![aaaaaa](https://user-images.githubusercontent.com/48137672/64986602-ad5aa080-d8c7-11e9-9fac-dfd14e9f3a4b.PNG)

when I remove dbname and let it dbname = ''
I got error when i reset/setup the database

![image](https://user-images.githubusercontent.com/48137672/64987659-f4499580-d8c9-11e9-8e08-62012faef439.png)

**Comment by MuAkl** [comment]
<?php
$XVWA_WEBROOT = "";
$host = "localhost";
$dbname = 'xvwa';
$user = "root";
$pass = "";
$conn = mysql_connect($host,$user,$pass);
$conn = mysql_select_db($dbname);
$conn1 = new PDO("mysql:host=$host;dbname=$dbname", $user, $pass);
$conn1->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
?>

**Comment by MuAql** [comment]
@s4n7h0

**Comment by s4n7h0** [comment]
@MuAkl - dbname is required for the application to work. This refers to database name. You will have to create mysql database with database name "dvwa". 

Have you tried using the auto setup script mentioned in the instructions ?

**Comment by MuAql** [comment]
yes I used the automatic script and the problem still occur,to solve it I've created the xvwa db manually ,Thank you
